site_name: Blog
nav: 
    - Home: index.md
    - About: about.md
    - Ansible: Ansible/devcontainer.md
theme: material
plugins:
    - awesome-pages
    - search
    - tags:
        enabled: true
extra:
    images: images/